//
//  ListGenresPresenter.swift
//  CleanPractice
//
//  Created by Ehsan on 12/04/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListGenresPresentable {
    func presentFetchedGenres(for response: ListGenresModels.Response)
}

class ListGenresPresenter: ListGenresPresentable {
    
    weak var viewController: ListGenresDisplayable?
  
    init(viewController: ListGenresDisplayable) {
        self.viewController = viewController
    }
    
    
    func presentFetchedGenres(for response: ListGenresModels.Response) {
        let viewModel = ListGenresModels.ViewModel(genres: response.genres)
        viewController?.displayGenres(with: viewModel)
    }
    
}
