//
//  ListGenresInteractor.swift
//  CleanPractice
//
//  Created by Ehsan on 12/04/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListGenresBusinessLogic {
//    func doSomething(request: ListGenres.Something.Request)
}

protocol ListGenresDataStore {
  //var name: String { get set }
}

class ListGenresInteractor: ListGenresBusinessLogic, ListGenresDataStore {
  var presenter: ListGenresPresentable?
  //var worker: ListGenresWorker?
  //var name: String = ""
  
    init(presenter: ListGenresPresentable) {
        self.presenter = presenter
    }
    
    
  // MARK: Do something
  
//    func doSomething(request: ListGenresModels.Request) {
//        worker = ListGenresWorker()
//        worker?.doSomeWork()
//
//        let response = ListGenresModels.Response()
//        presenter?.presentSomething(response: response)
//    }
}
