//
//  ListGenresRouter.swift
//  CleanPractice
//
//  Created by Ehsan on 12/04/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListGenresRoutable {
//    func doSomething()
}


class ListGenresRouter: ListGenresRoutable {
    
    weak var viewController: UIViewController?
    
    init(viewController: UIViewController) {
        self.viewController = viewController
    }
    
    
    func showGenre(genre: Genre) {
        let vc = ShowGenreViewController()
        vc.router.genre = genre
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    
}
