//
//  ListGenresInteractor.swift
//  CleanPractice
//
//  Created by Ehsan on 12/04/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ListGenresBusinessLogic {
    func fetchGenres(with request: ListGenresModels.Request)
}

protocol ListGenresDataStore {
  //var name: String { get set }
}

class ListGenresInteractor: ListGenresBusinessLogic, ListGenresDataStore {
    
    var presenter: ListGenresPresentable?
    var worker = JSONParser()
    
    init(presenter: ListGenresPresentable) {
        self.presenter = presenter
    }
    
    
    func fetchGenres(with request: ListGenresModels.Request) {
        worker.parseGenres { (genres) in
            do {
                let value = try genres.get()
                let response = ListGenresModels.Response(genres: value)
                self.presenter?.presentFetchedGenres(for: response)
            } catch {
                print(error)
            }
        }
    }
    
}
