//
//  ShowGenreViewController.swift
//  CleanPractice
//
//  Created by Ehsan on 12/04/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol ShowGenreDisplayable: class {
//    func displaySomething(viewModel: ShowGenreModels.ViewModel)
    // func to display error can be added here
}

class ShowGenreViewController: UIViewController, ShowGenreDisplayable {
//    lazy var interactor: ShowGenreBusinessLogic
//    lazy var router: ShowGenreRoutable
//    var viewModel: ShowGenreModels.ViewModel?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        //doSomething()
    }
    
    // MARK: Do something
    
//    func doSomething() {
//        let request = ShowGenre.Something.Request()
//        interactor?.doSomething(request: request)
//    }
//
//    func displaySomething(viewModel: ShowGenreModels.ViewModel) {
//        //nameTextField.text = viewModel.name
//    }
}
