//
//  MapModels.swift
//  RSR
//
//  Created by Ehsan on 06/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit
import CoreLocation

enum MapModels {
    /// Use case  to AskForPermission
    enum AskForPermission {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    /// Use case to LocateTheUser
    enum LocateTheUser {
        struct Request {
        }
        
        struct Response {
            let location: CLLocation
        }
        
        struct ViewModel {
            let address: String
            let coordinate: CLLocationCoordinate2D
        }
    }
    
    /// Use case to show the proper UI elements based on device type
    enum ShowElementsForDevice {
        struct Request {
        }
        
        struct Response {
            let deviceType: DeviceType
        }
        
        struct ViewModel {
            let deviceType: DeviceType
        }
    }
    
    /// Use case  to check internet connection
    enum CheckInternetConnection {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    /// Use case to open app URL
    enum OpenAppURL {
        struct Request {
        }
    }
    
    /// Use case to initiate a phone call
    enum CallTheCenter {
        struct Request {
        }
    }
}
