//
//  MainPresenter.swift
//  RSR
//
//  Created by Ehsan on 05/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol MainPresentable {
    func presentPrivacyAlert(response: MainModels.AskForUserConsent.Response)
    func presentElementsForDeviceType(response: MainModels.ShowElementsForDevice.Response)
}

class MainPresenter: MainPresentable {
    weak var viewController: MainDisplayable?
  
    init(viewController: MainDisplayable) {
        self.viewController = viewController
    }
    
    func presentPrivacyAlert(response: MainModels.AskForUserConsent.Response) {
        let viewModel = MainModels.AskForUserConsent.ViewModel()
        viewController?.displayPrivacyAlert(viewModel: viewModel)
    }
    
    func presentElementsForDeviceType(response: MainModels.ShowElementsForDevice.Response) {
        let viewModel = MainModels.ShowElementsForDevice.ViewModel(deviceType: response.deviceType)
        viewController?.displayElementsForDeviceType(viewModel: viewModel)
    }
    
  // MARK: Boiler plate code
  
//    func presentSomething(response: MainModels.Response) {
//        let viewModel = MainModels.ViewModel()
//
//        viewController?.displaySomething(viewModel: viewModel)
//    }
}
