//
//  AboutModels.swift
//  RSR
//
//  Created by Ehsan on 11/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

enum AboutModels {
    /// Use case to show the proper UI elements based on device type
    enum ShowElementsForDevice {
        struct Request {
        }
        
        struct Response {
            let deviceType: DeviceType
        }
        
        struct ViewModel {
            let deviceType: DeviceType
        }
    }
}
