//
//  AboutPresenter.swift
//  RSR
//
//  Created by Ehsan on 11/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol AboutPresentable {
    func presentElementsForDeviceType(response: AboutModels.ShowElementsForDevice.Response)
//    func presentSomething(response: AboutModels.Response)
}

class AboutPresenter: AboutPresentable {
    weak var viewController: AboutDisplayable?
  
    init(viewController: AboutDisplayable) {
        self.viewController = viewController
    }
    
    func presentElementsForDeviceType(response: AboutModels.ShowElementsForDevice.Response) {
        let viewModel = AboutModels.ShowElementsForDevice.ViewModel(deviceType: response.deviceType)
        viewController?.displayElementsForDeviceType(viewModel: viewModel)
    }
    
  // MARK: Boiler plate code 
  
//    func presentSomething(response: AboutModels.Response) {
//        let viewModel = AboutModels.ViewModel()
//
//        viewController?.displaySomething(viewModel: viewModel)
//    }
    
}
