//
//  AboutViewController.swift
//  RSR
//
//  Created by Ehsan on 11/03/2020.
//  Copyright (c) 2020 Ali C. All rights reserved.
//
//  This file was generated by Ali Chegini.
//  This is a simplified version of the Clean Swift Xcode Templates so
//  one can apply clean architecture to iOS and Mac projects.
//  For more info visit: http://clean-swift.com
//

import UIKit

protocol AboutDisplayable: class {
    /**
    Displays appropriate UI elements based on device type
    - Parameter viewModel: indicating device type (iPad or iPhone)
    */
    func displayElementsForDeviceType(viewModel: AboutModels.ShowElementsForDevice.ViewModel)
    
    //func displaySomething(viewModel: AboutModels.ViewModel)
}

class AboutViewController: UIViewController, AboutDisplayable {
    lazy var interactor: AboutBusinessLogic = AboutInteractor(presenter: AboutPresenter(viewController: self))
    //lazy var router: AboutRoutable
        
    @IBOutlet private weak var logoImageView: UIImageView!
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        checkDeviceType()
    }
    
    fileprivate func checkDeviceType() {
        let request = AboutModels.ShowElementsForDevice.Request()
        interactor.checkDeviceType(request: request)
    }
    
    func displayElementsForDeviceType(viewModel: AboutModels.ShowElementsForDevice.ViewModel) {
        if viewModel.deviceType == .pad {
            logoImageView.isHidden = false
        }
    }
    
    // MARK: Boiler plate code 
    
//    func doSomething() {
//        let request = About.Something.Request()
//        interactor?.doSomething(request: request)
//    }
//
//    func displaySomething(viewModel: AboutModels.ViewModel) {
//        //nameTextField.text = viewModel.name
//    }
}
